version: "3.9"

services:

  front:
    build: ./front
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  database:
    image: mongo
    volumes:
      - type: bind
        source: ./data
        target: /data/db

    ports:
      - "27015:27017"
